-- MySQL Script generated by MySQL Workbench
-- Mon 28 Jan 2019 05:12:16 PM EST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema pinedesk
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pinedesk
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pinedesk` DEFAULT CHARACTER SET utf8 ;
USE `pinedesk` ;

-- -----------------------------------------------------
-- Table `pinedesk`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pinedesk`.`users` (
  `userid` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NOT NULL,
  `passhash` VARCHAR(255) NULL,
  `google` TINYINT(1) NULL DEFAULT 0,
  `firstname` VARCHAR(100) NULL,
  `lastname` VARCHAR(100) NULL,
  `room` CHAR(3) NOT NULL,
  PRIMARY KEY (`userid`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pinedesk`.`groups`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pinedesk`.`groups` (
  `groupid` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(25) NOT NULL,
  `admin` INT NOT NULL,
  `description` VARCHAR(200) NULL,
  `longname` VARCHAR(50) NULL,
  PRIMARY KEY (`groupid`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC),
  INDEX `fk_groups_admin_idx` (`admin` ASC),
  CONSTRAINT `fk_groups_admin`
    FOREIGN KEY (`admin`)
    REFERENCES `pinedesk`.`users` (`userid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pinedesk`.`tickets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pinedesk`.`tickets` (
  `ticketid` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(100) NOT NULL,
  `description` LONGTEXT NULL,
  `reporter` INT NOT NULL,
  `assignee` INT NULL DEFAULT NULL,
  `reportdate` TIMESTAMP NOT NULL,
  `completedate` TIMESTAMP NULL,
  `group` INT NOT NULL,
  `status` VARCHAR(45) NOT NULL DEFAULT 'Unassigned',
  `global` TINYINT(1) NULL DEFAULT 0,
  PRIMARY KEY (`ticketid`),
  INDEX `fk_tickets_reporter_idx` (`reporter` ASC),
  INDEX `fk_tickets_assignee_idx` (`assignee` ASC),
  INDEX `fk_tickets_group_idx` (`group` ASC),
  CONSTRAINT `fk_tickets_reporter`
    FOREIGN KEY (`reporter`)
    REFERENCES `pinedesk`.`users` (`userid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tickets_assignee`
    FOREIGN KEY (`assignee`)
    REFERENCES `pinedesk`.`users` (`userid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tickets_group`
    FOREIGN KEY (`group`)
    REFERENCES `pinedesk`.`groups` (`groupid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pinedesk`.`tcomments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pinedesk`.`tcomments` (
  `commentid` INT NOT NULL AUTO_INCREMENT,
  `ticketid` INT NOT NULL,
  `postdate` TIMESTAMP NOT NULL,
  `content` LONGTEXT NULL,
  `statuschange` TINYINT(1) NULL DEFAULT 0,
  PRIMARY KEY (`commentid`, `ticketid`),
  INDEX `fk_tcomments_ticketid_idx` (`ticketid` ASC),
  CONSTRAINT `fk_tcomments_ticketid`
    FOREIGN KEY (`ticketid`)
    REFERENCES `pinedesk`.`tickets` (`ticketid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pinedesk`.`tattach`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pinedesk`.`tattach` (
  `attachmentid` INT NOT NULL AUTO_INCREMENT,
  `ticketid` INT NOT NULL COMMENT '			',
  `filepath` VARCHAR(4096) NOT NULL,
  PRIMARY KEY (`attachmentid`, `ticketid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pinedesk`.`gmembers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pinedesk`.`gmembers` (
  `groupid` INT NOT NULL,
  `userid` INT NOT NULL,
  PRIMARY KEY (`groupid`, `userid`),
  INDEX `fk_gmembers_userid_idx` (`userid` ASC),
  CONSTRAINT `fk_gmembers_groupid`
    FOREIGN KEY (`groupid`)
    REFERENCES `pinedesk`.`groups` (`groupid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_gmembers_userid`
    FOREIGN KEY (`userid`)
    REFERENCES `pinedesk`.`users` (`userid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
